server:
  port: 7788

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# ???? thymeleaf ???????
  thymeleaf:
    prefix: classpath:/templates/
